Universe	= vanilla
Executable	= scriptForQACentrality.sh
Output          = INITDIR/condor_$(runnumber).out
Error           = INITDIR/condor_$(runnumber).err
Log             = INITDIR/condor_$(runnumber).log
Arguments       = "$(runnumber)"
Initialdir      = INITDIR
PeriodicHold 	= (NumJobStarts>=1 && JobStatus == 1)
request_memory = 4096MB

transfer_input_files = setup_env.sh, submit_file.txt, container_scriptForQACentrality.sh

