Universe	= vanilla
Executable	= scriptForQACentrality.sh
Output          = condor_$(Process).out
Error           = condor_$(Process).err
Log             = condor_$(Process).log
Arguments       = "$(Process) COPYDIR"
Initialdir      = INITDIR
PeriodicHold 	= (NumJobStarts>=1 && JobStatus == 1)
request_memory = 4096MB

transfer_input_files = setup_env.sh, submit_file.txt, container_scriptForQACentrality.sh

